version: '3.11.5'

services:
  app:
    build: .
    volumes:
          - .:/web
    ports:
        - "8000:8000"
    image: app:web
    container_name: my_django_container
    command: python manage.py runserver 0.0.0.0:8000
    
