# Generated by Django 4.2.11 on 2024-05-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_id',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
