# Generated by Django 4.2.11 on 2024-05-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_firebase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firebase_id',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
